### ISSUE TITLE
dm6 gene names on chromosomes other than chrX are not found

### ISSUE THREAD

**Issue by gvogler** [gladkia/igvR#18]
I run data on the Drosophila dm6 genome and noticed that only genes from chrX are recognized and found (search box or via showGenomicRegion), but no gene on other chromosomes
```
igv <- igvR()
setBrowserWindowTitle(igv, "igvR Dmel")
setGenome(igv, "dm6")

showGenomicRegion(igv, "w")
[1] "w"
showGenomicRegion(igv, "Msp300")
[1] "unrecognized locus 'Msp300'"
```
The transcript of Msp300 is present in the track view and I can navigate their with coordinates, just not by gene. The standalone igv program can find those genes.

**Comment by paul-shannon** [comment]
@gvogler - working on this now, taking some notes.
Msp300's coordinates: chr2L:5,100,877-5,207,002
bypassing igvR/javascript message passing, trying your test case in the javascript browser console, I think the problem lies in igv.js.  I will put the question to Jim Robinson, who is always responsive and helpful.
```
igv.version() // '2.10.5'
p1 = igvBrowser.search("chr2L:5,100,877-5,207,002") // this works
p2 = igvBrowser.search("Msp300")  // this fails 
```
```search``` returns a Promise which, when examined for each of these cases, looks like this:
![image](https://user-images.githubusercontent.com/2480712/158479338-bbc7dc50-50fa-4b6d-be84-a47ac7fdc0a2.png)

**Comment by paul-shannon** [comment]
@gvogler Jim Robinson says this is now fixed: https://github.com/igvteam/igv.js/issues/1476#issuecomment-1082296795
Could you give it a try?

**Comment by gvogler** [comment]
Perfect! Works like a charm.

**Comment by paul-shannon** [comment]
glad to hear it!
