### ISSUE TITLE
Custom color for Chromosome in GWASTrack() (Bug in igvR)

### ISSUE THREAD

**Issue by ladyson1806** [gladkia/igvR#24]
@paul-shannon - Hi Paul,

Thank you for your hard work on this Shiny app! The app is easy to use, and my work is nicely displayed. 
I have an issue regarding the colour scheme of the GWAS track when I am displaying my results, and I hope you can help me to solve it. 

____

### Context 
I want to display my custom GWAS results along the yeast genome (SacCer3 that I load from the IGV database). I need to show several GWAS tracks to compare multiple conditions. Here is an example :
![image](https://user-images.githubusercontent.com/17936544/209678067-377729a2-88e8-4c6d-9a29-8fce69f8e7cd.png)

____

#### 1) Differences in color scheme for two different GWAS tracks along the same genome
- I should have the same colour scheme for the two GWAS tracks that I am displaying (since I have the same number of chromosomes on my genome and the difference between the two GWAS tracks are simply changes of p-values). As you can see, there are differences in the colour scheme of the two GWAS tracks. 

#### 2) How to customize the color scheme of the chromosome in GWAS Track?
- I don't need multiple colours for the chromosomes on these GWAS tracks. I want to simplify the colour scheme by using a bicolour scale to differentiate the neighbouring chromosomes. For example, with this kind of pattern: 

> `colors <- rep(c('black', 'grey'), times = 8, length.out = 17)`

- I tried to use the parameter colour from `GWASTrack()` to change the colour scheme, but I don't think this is the correct use. 

____

Thank you in advance for your help.
Merry Christmas! I wish you the best for the end of the year.

Savvy

**Comment by paul-shannon** [comment]
@ladyson1806 - Savvy,  Thank you for this bug report.  I will look into later today or tomorrow, hoping then to give you a quick fix.

**Comment by paul-shannon** [comment]
@ladyson1806 - Hi Savvy,

I just put in a couple of hours on this, found a bug (unrelated to yours), fixed it, and now, if I may, I have some questions for you.  

First: the current ```igvShiny``` GWASTrack.R has no color parameter.   But the ```igvR``` GWASTrack.R does - though, as you perhaps point out, it is ignored.   I may be confused, but is it possible you are using igvR rather than igvShiny?  I'll be happy to turn my attention to igvR if that is the case.  Please provide your ```sessionInfo()``` also!

Second: can you give me access to your gwas files?  Or a subset that reproduces the problem.   In my tests, the colors are the same in two successive tracks.

Third:  I see that the igv.js team does not yet provide color options for the underlying GWAS track.   They are often responsive to feature requests, which I could ask of them once I have a reproducible example.

 - Paul

**Comment by ladyson1806** [comment]
@paul-shannon - Hi Paul,

Thank you for taking some time to take a look at my request!

1) You are right. The bug I mentioned is from `igvR` (I mistook `igvR` for `igvShiny` because I made a custom Shiny wrapper  that relies on the igvR package). To avoid further confusion, I modified the title of my issue. 
The bug seems to come from the function `GWASTrack()` from `igvR`.

___

Here is my `sessionInfo()` for my issue: 
![image](https://user-images.githubusercontent.com/17936544/210061195-3f696886-a13e-42bd-9787-52ff8bfc572f.png)

___

2) You can use these two files to reproduce the problem I initially mentioned: 
- [noPPI_reference_MTX_noDrug_avg_logratio_Fitness_minus_ref.csv](https://github.com/paul-shannon/igvShiny/files/10324215/noPPI_reference_MTX_noDrug_avg_logratio_Fitness_minus_ref.csv)
- [noPPI_reference_noMTX_noDrug_avg_logratio_Fitness_minus_ref.csv](https://github.com/paul-shannon/igvShiny/files/10324218/noPPI_reference_noMTX_noDrug_avg_logratio_Fitness_minus_ref.csv)

The code below should work on these two tables once they are put in a folder called `./data_test/` in your working directory. 

```
library(igvR)
library(glue)

romanize <- function(x) {
  if (class(x) == 'integer') as.roman(x)
  else x
}

##### Load Yeast Genome

igv <- igvR()
setBrowserWindowTitle(igv, "Interactive Genome Browser - GWAS demo")
setGenome(igv, "sacCer3")

##### Load GWAS Tracks
PPI = 'noPPI_reference'
DRUG = 'noDrug'

MTX_infile = paste0(getwd(), glue('/data_test/{PPI}_MTX_{DRUG}_avg_logratio_Fitness_minus_ref.csv'))
MTX_table <- read.csv(MTX_infile)
MTX_table['CHR_igv'] <- lapply(MTX_table['CHR'], romanize)
MTX_table = MTX_table[c("SNP", "CHR_igv", "BP", "EFFECTSIZE", "SE", "P", "snps_class_up", "snps_class_down", "locus_id", "GENE", "sgd_id")]
MTX_track <- GWASTrack(glue('{PPI} under {DRUG} (MTX+)'), MTX_table, chrom.col=2, pos.col=3, pval.col=6, trackHeight=200)
displayTrack(igv, MTX_track)

noMTX_infile = paste0(getwd(), glue('/data_test/{PPI}_noMTX_{DRUG}_avg_logratio_Fitness_minus_ref.csv'))
noMTX_table <- read.csv(noMTX_infile)
noMTX_table['CHR_igv'] <- lapply(noMTX_table['CHR'], romanize)
noMTX_table = noMTX_table[c("SNP", "CHR_igv", "BP", "EFFECTSIZE", "SE", "P", "snps_class_up", "snps_class_down", "locus_id", "GENE", "sgd_id")]
noMTX_track <- GWASTrack(glue('{PPI} under {DRUG} (MTX+)'), noMTX_table, chrom.col=2, pos.col=3, pval.col=6, trackHeight=200)
displayTrack(igv, noMTX_track)
```
___

This provide these GWAS tracks :

![IGV_GWAS_Track_color_bug](https://user-images.githubusercontent.com/17936544/210062512-e7d5b015-6348-4432-a754-53909ecd91b3.png) 

- I highlighted with a square the color scheme that are not similar between the two GWAS tracks. 

___

3) If you could ask the igv.js team to add this new feature, it would be nice!  
To illustrate the type of colour scheme I would like to display, here is a screen of a Manhattan plot (the same as the top GWAS Track) I was able to generate with the library `manhanttanly`. This library is an alternative to display my GWAS track, but they don't include the genome annotations like IGV does (which I would prefer to use for my project).
<br>

![newplot](https://user-images.githubusercontent.com/17936544/210063469-045808c5-e3d8-47fe-84ca-b375c76a9b5a.png)

__

Thanks again, 
Have a nice day.

Savvy

**Comment by paul-shannon** [comment]
@ladyson1806 - Savvy,

Sorry for my delay in getting back to this.   I just reproduced the color inconsistency problem in a minimal example for Jim Robinson [here].(https://github.com/igvteam/igv.js/issues/1573)

When I hear back from him, I will ask for his thoughts on adding more color options.  Perhaps he can add support for a vector of color names as an extra parameter.   This would accomplish your alternating light & dark color scheme simply by saying something like:
```
colors <- c("black", "lightgray")
```
If you provide as many colors as there are chromosomes, then that is what you would see.   More flexible still would be a list of color vectors, each vector associated with a number,  so that gwas pvals above specified thresholds could be displayed in different colors.

Let's see if Jim can solve the basic problem first - or maybe point out an error in my usage.

**Comment by paul-shannon** [comment]
@ladyson1806 - Savvy, this may have take too long to do you much good, but here's to let you know that igvR now supports the gwas color flexibility Jim Robinson recently added to igv.js.

package version 1.19.1, with sample use in ```inst/demos/gwasDemo.R```

**Comment by ladyson1806** [comment]
It is fixed now! 
Thank you for your help @paul-shannon

**Comment by ladyson1806** [comment]
It is fixed now!
Thank you for your help @paul-shannon
