### ISSUE TITLE
Encountering an issue with importing data from a URL that I created myself

### ISSUE THREAD

**Issue by daxiaodi** [gladkia/igvR#27]
Hi Paul,

I am using the igvR package and encountering an issue with importing data from a URL that I created myself.
I have successfully run the example file provided with the software and downloaded it. Afterward, I uploaded the downloaded file to my personal cloud storage and obtained a URL for it. However, when I attempt to use igvR to read the data from the URL I created, it fails to do so. 

I would greatly appreciate it if you could provide some guidance on how to resolve this problem.

Best,
Xiaowei

**Comment by paul-shannon** [comment]
Hi @daxiaodi,

The first thing to check is the CORS and byte-range capabilities of your personal cloud storage web server.
Here is an example of checking those things from the command line, for an aws server.  The "Origin:" argument is made up; you can substitute, if you wish,  a url more meaningful to you.    But note that if, as we see below, ```Access-Control-Allow-Orgin: *``` is set, any host can make a CORS request.

Let me know if this helps.
Configuring a webserver can be confusing, at least for me.
FWIW, I run a cors- and byte-range-enabled nginx webserver on my laptop, inside a docker container, eliminating much of the confusion I otherwise have encountered.

```
 curl -L -H "Access-Control-Request-Method: GET" -H "Origin: http://riptide.systemsbiology.net" --head https://s3.amazonaws.com/igv.org.demo/nstd186.GRCh38.variant_call.vcf.gz
```
Here is the response, with good status reported (cors & byte-range):
```
HTTP/1.1 200 OK
x-amz-id-2: xo1KOoJRHBDXt99IJE0S25/z0oJhX0N1i6YsUN6ozrhdeF6zlbSXVMnAXw0h/dfAmQDMPACA0HY=
x-amz-request-id: BE7VGVAYEYTD7CPS
Date: Wed, 14 Jun 2023 16:45:28 GMT
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: GET, HEAD
Access-Control-Expose-Headers: Content-Length, Content-Type, Content-Range
Access-Control-Max-Age: 3000
Vary: Origin, Access-Control-Request-Headers, Access-Control-Request-Method
Last-Modified: Thu, 01 Apr 2021 17:00:26 GMT
ETag: "54608fe9fedf3a0aab03b80038293349"
Accept-Ranges: bytes
Content-Type: application/x-gzip
Server: AmazonS3
Content-Length: 4003352
```

**Comment by paul-shannon** [comment]
Please see this vignette:  https://paul-shannon.github.io/igvR/articles/v02.customGenome.html

**Comment by daxiaodi** [comment]
Hi @paul-shannon ,

Thanks for the reply. It works!

Best,
Xiaowei
